import React, { useCallback, useEffect, useState } from "react";

type Role = { id: string; name: string; displayName: string };
type TenantUser = { id: string; firstName: string; lastName: string; email: string; accountStatus: string; membershipStatus: string; membershipVersion: number; roleId: string; roleName: string; organizationName?: string };
type Invitation = { id: string; email: string; status: string; roleName: string; createdAt: string; expiresAt: string };
const API = "http://localhost:8080";
const control: React.CSSProperties = { minHeight: 44, border: "1px solid #94a3b8", borderRadius: 6, padding: "8px 10px", font: "inherit" };
const button: React.CSSProperties = { ...control, cursor: "pointer", background: "#0f766e", color: "white", fontWeight: 700 };

export function UsersAccessPage({ token, currentUserId }: { token: string; currentUserId: string }) {
  const [tab, setTab] = useState<"users" | "invitations">("users");
  const [users, setUsers] = useState<TenantUser[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [roles, setRoles] = useState<Role[]>([]);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [role, setRole] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [showInvite, setShowInvite] = useState(false);
  const auth = { Authorization: `Bearer ${token}` };
  const request = useCallback(async (path: string, init?: RequestInit) => { const response = await fetch(`${API}${path}`, { ...init, headers: { ...auth, ...(init?.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Request failed"); return data; }, [token]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ limit: "25", offset: "0" }); if(search)query.set("search",search);if(status)query.set("status",status);if(role)query.set("role",role); const [roleRows, rows] = await Promise.all([request("/users/roles"), request(tab === "users" ? `/users?${query}` : `/users/invitations?${query}`)]); setRoles(roleRows); tab === "users" ? setUsers(rows) : setInvitations(rows); } catch(e){setError(e instanceof Error?e.message:"Unable to load Users & Access");} finally{setLoading(false);} },[request,tab,search,status,role]);
  useEffect(()=>{void load();},[load]);
  const mutate = async (path:string, method="POST", body?:object) => { setError("");setMessage("");try{await request(path,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});setMessage("Changes saved successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Change failed");} };
  const changeRole = async (user:TenantUser) => { const roleId=window.prompt("Enter the approved role ID shown in the role selector:",user.roleId);if(!roleId||roleId===user.roleId)return;const reason=window.prompt("Reason for changing this role (sessions will be revoked):");if(!reason)return;await mutate(`/users/${user.id}/role`,"PATCH",{roleId,expectedVersion:user.membershipVersion,reason}); };
  const changeStatus = async (user:TenantUser) => { const next=user.accountStatus==="suspended"?"active":"suspended";if(!window.confirm(`${next==="suspended"?"Suspend":"Reactivate"} ${user.firstName} ${user.lastName}? Their sessions will be revoked.`))return;const reason=window.prompt("Reason for this status change:");if(!reason)return;await mutate(`/users/${user.id}/status`,"PATCH",{status:next,expectedVersion:user.membershipVersion,reason}); };
  return <section aria-labelledby="users-access-title" style={{maxWidth:1200,margin:"0 auto"}}>
    <style>{`.iam-control:focus-visible{outline:3px solid #0ea5e9;outline-offset:2px}.iam-table-wrap{overflow-x:auto}.iam-table{width:100%;border-collapse:collapse;min-width:760px}.iam-table th,.iam-table td{padding:12px;text-align:left;border-bottom:1px solid #e2e8f0}@media(max-width:600px){.iam-toolbar{align-items:stretch!important}.iam-toolbar>*{width:100%}}`}</style>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap"}}><div><h1 id="users-access-title">Users &amp; Access</h1><p>Manage tenant users, approved roles, invitations, and access status.</p></div><button className="iam-control" style={button} onClick={()=>setShowInvite(true)}>Invite user</button></div>
    <div role="tablist" aria-label="Users and invitations" style={{display:"flex",gap:8,margin:"20px 0"}}>{(["users","invitations"] as const).map(value=><button className="iam-control" role="tab" aria-selected={tab===value} key={value} onClick={()=>setTab(value)} style={{...button,background:tab===value?"#0f766e":"#e2e8f0",color:tab===value?"white":"#0f172a"}}>{value==="users"?"Users":"Invitations"}</button>)}</div>
    <div className="iam-toolbar" style={{display:"flex",alignItems:"end",gap:10,flexWrap:"wrap"}}><label>Search<br/><input className="iam-control" style={control} value={search} onChange={e=>setSearch(e.target.value)} /></label><label>Status<br/><select className="iam-control" style={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{(tab==="users"?["active","invited","suspended"]:["pending","accepted","expired","revoked","superseded"]).map(value=><option key={value}>{value}</option>)}</select></label><label>Role<br/><select className="iam-control" style={control} value={role} onChange={e=>setRole(e.target.value)}><option value="">All</option>{roles.map(item=><option key={item.id} value={item.name}>{item.displayName}</option>)}</select></label></div>
    <div aria-live="polite" style={{minHeight:28,marginTop:12,color:error?"#b91c1c":"#166534"}}>{error||message}</div>
    {loading?<p>Loading tenant access records…</p>:tab==="users"?<div className="iam-table-wrap"><table className="iam-table"><caption className="sr-only">Tenant users</caption><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Organization</th><th>Actions</th></tr></thead><tbody>{users.length===0?<tr><td colSpan={6}>No users found.</td></tr>:users.map(user=><tr key={user.id}><td>{user.firstName} {user.lastName}{user.id===currentUserId?" (You)":""}</td><td>{user.email}</td><td>{user.roleName==="environmental_consultant"?"Environmental Consultant / Subcontractor":user.roleName}</td><td>{user.accountStatus}</td><td>{user.organizationName||"Tenant-wide"}</td><td style={{display:"flex",gap:8}}><button className="iam-control" style={control} disabled={user.id===currentUserId||user.roleName==="super_admin"} title={user.id===currentUserId?"You cannot change your own role":undefined} onClick={()=>void changeRole(user)}>Change role</button><button className="iam-control" style={control} disabled={user.id===currentUserId} onClick={()=>void changeStatus(user)}>{user.accountStatus==="suspended"?"Activate":"Suspend"}</button></td></tr>)}</tbody></table></div>:<div className="iam-table-wrap"><table className="iam-table"><caption className="sr-only">Tenant invitations</caption><thead><tr><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{invitations.length===0?<tr><td colSpan={6}>No invitations found.</td></tr>:invitations.map(invite=><tr key={invite.id}><td>{invite.email}</td><td>{invite.roleName==="environmental_consultant"?"Environmental Consultant / Subcontractor":invite.roleName}</td><td>{invite.status}</td><td>{new Date(invite.createdAt).toLocaleString()}</td><td>{new Date(invite.expiresAt).toLocaleString()}</td><td style={{display:"flex",gap:8}}><button className="iam-control" style={control} disabled={invite.status!=="pending"} onClick={()=>void mutate(`/users/invitations/${invite.id}/resend`)}>Resend</button><button className="iam-control" style={control} disabled={invite.status!=="pending"} onClick={()=>window.confirm("Revoke this pending invitation?")&&void mutate(`/users/invitations/${invite.id}/revoke`)}>Revoke</button></td></tr>)}</tbody></table></div>}
    {showInvite&&<InviteDialog roles={roles} onClose={()=>setShowInvite(false)} onSubmit={async body=>{await request("/users/invitations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});setShowInvite(false);setTab("invitations");setMessage("Invitation queued securely.");await load();}} />}
  </section>;
}

function InviteDialog({roles,onClose,onSubmit}:{roles:Role[];onClose:()=>void;onSubmit:(body:object)=>Promise<void>}){const[firstName,setFirst]=useState("");const[lastName,setLast]=useState("");const[email,setEmail]=useState("");const[roleId,setRole]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");return <div role="dialog" aria-modal="true" aria-labelledby="invite-title" style={{position:"fixed",inset:0,zIndex:1000,background:"#0f172acc",display:"grid",placeItems:"center",padding:16}}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await onSubmit({firstName,lastName,email,roleId});}catch(err){setError(err instanceof Error?err.message:"Invitation failed");setBusy(false);}}} style={{background:"white",borderRadius:10,padding:24,width:"min(460px,100%)",display:"grid",gap:14}}><h2 id="invite-title">Invite user</h2><label>First name<input autoFocus required className="iam-control" style={{...control,width:"100%"}} value={firstName} onChange={e=>setFirst(e.target.value)}/></label><label>Last name<input required className="iam-control" style={{...control,width:"100%"}} value={lastName} onChange={e=>setLast(e.target.value)}/></label><label>Email<input required type="email" className="iam-control" style={{...control,width:"100%"}} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Approved tenant role<select required className="iam-control" style={{...control,width:"100%"}} value={roleId} onChange={e=>setRole(e.target.value)}><option value="">Select role</option>{roles.map(role=><option key={role.id} value={role.id}>{role.displayName}</option>)}</select></label><p style={{color:"#475569"}}>Invitation acceptance is subject to verification. No activation token will be displayed here.</p>{error&&<p role="alert" style={{color:"#b91c1c"}}>{error}</p>}<div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" className="iam-control" style={control} onClick={onClose}>Cancel</button><button disabled={busy} className="iam-control" style={button}>{busy?"Sending…":"Send invitation"}</button></div></form></div>}
