import crypto from "node:crypto";
import type { Pool, PoolClient } from "pg";

export const WF_RUNTIME_BATCH_SIZE=100;
export const WF_RUNTIME_LEASE_SECONDS=60;
export const WF_RUNTIME_MAX_ATTEMPTS=5;

const digest=(value:unknown)=>crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");

export class WorkflowRuntimeWorker {
  constructor(private readonly pool:Pool,private readonly owner=`wf-worker-${crypto.randomUUID()}`){}

  async scheduleDue():Promise<number>{
    const c=await this.pool.connect();
    try{await c.query("BEGIN");const due=await c.query(`SELECT t.*,i.organization_id FROM workflow_timer t JOIN workflow_instance i ON i.tenant_id=t.tenant_id AND i.id=t.instance_id JOIN tenant ten ON ten.id=t.tenant_id AND ten.status='active' JOIN organization o ON o.tenant_id=i.tenant_id AND o.id=i.organization_id AND o.status='active' WHERE t.status='pending' AND t.due_at<=NOW() ORDER BY t.due_at,t.id LIMIT $1 FOR UPDATE OF t SKIP LOCKED`,[WF_RUNTIME_BATCH_SIZE]);
      for(const timer of due.rows){const taskId=`wf.timer:${timer.tenant_id}:${timer.id}:${timer.timer_type}`;const task=await c.query(`INSERT INTO task_execution(tenant_id,task_id,task_type,payload_hash,status,available_at,attempt_count,max_attempts,encrypted_payload) VALUES($1,$2,'govos.workflow.timer',$3,'pending',NOW(),0,$4,$5) ON CONFLICT(tenant_id,task_id) DO UPDATE SET available_at=LEAST(task_execution.available_at,EXCLUDED.available_at) RETURNING id`,[timer.tenant_id,taskId,digest({timerId:timer.id,type:timer.timer_type}),WF_RUNTIME_MAX_ATTEMPTS,JSON.stringify({schemaVersion:'wf1',timerId:timer.id})]);await c.query(`UPDATE workflow_timer SET status='leased',task_execution_id=$1,lease_owner=NULL,lease_expires_at=NULL WHERE tenant_id=$2 AND id=$3 AND status='pending'`,[task.rows[0].id,timer.tenant_id,timer.id]);}
      await c.query("COMMIT");return due.rowCount??0;
    }catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}
  }

  async runDueTasks():Promise<number>{const tasks=await this.pool.query(`UPDATE task_execution SET status='processing',lease_owner=$1,lease_expires_at=NOW()+($2||' seconds')::interval,last_heartbeat_at=NOW(),attempt_count=attempt_count+1,fencing_token=fencing_token+1,updated_at=NOW() WHERE id IN (SELECT id FROM task_execution WHERE task_type='govos.workflow.timer' AND available_at<=NOW() AND (status IN ('pending','retryable_failed') OR (status='processing' AND lease_expires_at<NOW())) ORDER BY available_at,id LIMIT $3 FOR UPDATE SKIP LOCKED) RETURNING *`,[this.owner,String(WF_RUNTIME_LEASE_SECONDS),WF_RUNTIME_BATCH_SIZE]);for(const task of tasks.rows)await this.executeTask(task);return tasks.rowCount??0;}

  private async executeTask(task:any){const c=await this.pool.connect();try{await c.query("BEGIN");const locked=await c.query(`SELECT * FROM task_execution WHERE id=$1 AND status='processing' AND lease_owner=$2 AND fencing_token=$3 AND lease_expires_at>NOW() FOR UPDATE`,[task.id,this.owner,task.fencing_token]);if(!locked.rowCount)throw new Error('WF_STALE_FENCE');const timerId=task.encrypted_payload?.timerId;const timer=await c.query(`SELECT t.*,i.organization_id,i.status instance_status,e.status execution_status FROM workflow_timer t JOIN workflow_instance i ON i.tenant_id=t.tenant_id AND i.id=t.instance_id LEFT JOIN workflow_step_execution e ON e.tenant_id=t.tenant_id AND e.id=t.step_execution_id WHERE t.id=$1 AND t.tenant_id=$2 FOR UPDATE OF t`,[timerId,task.tenant_id]);if(!timer.rowCount)throw new Error('WF_TIMER_MISSING');const row=timer.rows[0];if(['completed','cancelled','failed'].includes(row.instance_status)||['completed','cancelled','skipped','dead_lettered'].includes(row.execution_status)){await c.query(`UPDATE workflow_timer SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL WHERE id=$1`,[row.id]);}else if(row.timer_type==='sla_reminder'){await this.processReminder(c,row);}else if(row.timer_type==='sla_breach'){await this.processBreach(c,row);}else throw new Error('WF_TIMER_POLICY_INVALID');await c.query(`UPDATE task_execution SET status='completed',completed_at=NOW(),lease_owner=NULL,lease_expires_at=NULL,updated_at=NOW() WHERE id=$1 AND lease_owner=$2 AND fencing_token=$3`,[task.id,this.owner,task.fencing_token]);await c.query("COMMIT");}catch(e){await c.query("ROLLBACK");const message=e instanceof Error?e.message:String(e);if(message==='WF_STALE_FENCE'){return;}const terminal=task.attempt_count>=task.max_attempts||/MISSING|INVALID|MISCONFIGURED/.test(message);await this.pool.query(`UPDATE task_execution SET status=$1,lease_owner=NULL,lease_expires_at=NULL,available_at=NOW()+(LEAST(300,10*POWER(2,GREATEST(attempt_count-1,0)))||' seconds')::interval,failure_code=$2,updated_at=NOW() WHERE id=$3 AND lease_owner=$4 AND fencing_token=$5`,[terminal?'permanently_failed':'retryable_failed',message.slice(0,80),task.id,this.owner,task.fencing_token]);await this.pool.query(`UPDATE workflow_timer SET status=$1,failure_code=$2 WHERE task_execution_id=$3 AND status='leased'`,[terminal?'failed':'pending',message.slice(0,80),task.id]);}finally{c.release();}}

  private async processReminder(c:PoolClient,timer:any){const clock=await c.query(`UPDATE workflow_sla_clock SET reminder_sent_at=COALESCE(reminder_sent_at,NOW()),version=version+1 WHERE tenant_id=$1 AND step_execution_id=$2 AND state='running' RETURNING *`,[timer.tenant_id,timer.step_execution_id]);if(!clock.rowCount)throw new Error('WF_SLA_CLOCK_MISSING');await this.assertRecipients(c,timer.tenant_id,timer.organization_id,clock.rows[0].policy_snapshot);await c.query(`UPDATE workflow_timer SET status='fired',fired_at=NOW(),lease_owner=NULL,lease_expires_at=NULL WHERE id=$1`,[timer.id]);}
  private async processBreach(c:PoolClient,timer:any){const clock=await c.query(`UPDATE workflow_sla_clock SET state='breached',breached_at=COALESCE(breached_at,NOW()),version=version+1 WHERE tenant_id=$1 AND step_execution_id=$2 AND state='running' RETURNING *`,[timer.tenant_id,timer.step_execution_id]);if(!clock.rowCount)throw new Error('WF_SLA_CLOCK_MISSING');const policy=clock.rows[0].policy_snapshot??{};await this.assertRecipients(c,timer.tenant_id,timer.organization_id,policy);const chain=Array.isArray(policy.escalations)?policy.escalations.slice(0,10):[];for(let index=0;index<chain.length;index++){const action=chain[index];if(!['notify','reassign'].includes(action.type))throw new Error('WF_ESCALATION_POLICY_INVALID');await c.query(`INSERT INTO workflow_escalation_action(tenant_id,sla_clock_id,level,action_type,idempotency_key,status,completed_at) VALUES($1,$2,$3,$4,$5,'completed',NOW()) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING`,[timer.tenant_id,clock.rows[0].id,index+1,action.type,`${clock.rows[0].id}:escalation:${index+1}:${action.type}`]);}await c.query(`UPDATE workflow_timer SET status='fired',fired_at=NOW(),lease_owner=NULL,lease_expires_at=NULL WHERE id=$1`,[timer.id]);}
  private async assertRecipients(c:PoolClient,tenantId:string,organizationId:string,policy:any){const roleIds=(policy.escalations??[]).map((x:any)=>x.roleId).filter(Boolean);const users=await c.query(`SELECT 1 FROM membership m JOIN user_account u ON u.tenant_id=m.tenant_id AND u.id=m.user_id AND u.status='active' JOIN organization o ON o.tenant_id=m.tenant_id AND o.id=m.organization_id AND o.status='active' WHERE m.tenant_id=$1 AND m.organization_id=$2 AND m.status='active' AND (cardinality($3::uuid[])=0 OR m.role_id=ANY($3::uuid[])) LIMIT 1`,[tenantId,organizationId,roleIds]);if(!users.rowCount)throw new Error('WF_QUEUE_MISCONFIGURED');}
}
