export declare enum RegistryErrorCode {
    APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND",
    AGENT_DEFINITION_NOT_FOUND = "AGENT_DEFINITION_NOT_FOUND",
    PROMPT_VERSION_NOT_FOUND = "PROMPT_VERSION_NOT_FOUND",
    OUTPUT_CONTRACT_VERSION_NOT_FOUND = "OUTPUT_CONTRACT_VERSION_NOT_FOUND",
    TOOL_VERSION_NOT_FOUND = "TOOL_VERSION_NOT_FOUND",
    MISMATCHED_APPLICATION_OWNERSHIP = "MISMATCHED_APPLICATION_OWNERSHIP",
    INVALID_JSON_SCHEMA = "INVALID_JSON_SCHEMA",
    INVALID_CONTENT_HASH = "INVALID_CONTENT_HASH",
    LIMITS_EXCEED_PLATFORM_MAX = "LIMITS_EXCEED_PLATFORM_MAX",
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION",
    IMMUTABLE_RECORD_MUTATION = "IMMUTABLE_RECORD_MUTATION",
    RETIRED_VERSION_REPLAY_REJECTED = "RETIRED_VERSION_REPLAY_REJECTED",
    REFERENCED_VERSION_NOT_ACTIVE = "REFERENCED_VERSION_NOT_ACTIVE",
    ACTIVATION_FAILED = "ACTIVATION_FAILED"
}
export declare class RegistryError extends Error {
    readonly code: RegistryErrorCode;
    constructor(code: RegistryErrorCode, message: string);
}
//# sourceMappingURL=registry-error-codes.d.ts.map