import React, { useEffect, useState } from "react";

type Props={apiBaseUrl:string;token:string;mode:"definitions"|"instances"|"tasks"|"operations"};
const headers=(token:string,extra:Record<string,string>={})=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json",...extra});
export function WorkflowWorkspace({apiBaseUrl,token,mode}:Props){
 const [data,setData]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[name,setName]=useState(""),[key,setKey]=useState("");
 const path=mode==='definitions'?'/v1/workflows/definitions':mode==='instances'?'/v1/workflows/instances':mode==='tasks'?'/v1/work-items':'/v1/workflows/operations';
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(apiBaseUrl+path,{headers:headers(token)});const body=await r.json();if(!r.ok)throw new Error(body.message||body.error||'Request failed');setData(Array.isArray(body)?body:[body]);}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[path,token]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();const model={steps:[{key:'start',name:'Start',type:'human_review',entry:true,assignment:{type:'organization_queue'}},{key:'complete',name:'Complete',type:'domain_command',terminal:true}],transitions:[{key:'complete',from:'start',to:'complete',outcome:'complete'}]};const r=await fetch(apiBaseUrl+'/v1/workflows/definitions',{method:'POST',headers:headers(token,{"Idempotency-Key":crypto.randomUUID()}),body:JSON.stringify({key,name,model})});if(r.ok){setKey('');setName('');await load();}else{const b=await r.json();setError(b.message||'Creation failed');}};
 const title=mode==='definitions'?'Workflow Definitions':mode==='instances'?'Workflow Instances':mode==='tasks'?'My Tasks & Queue':'SLA & Escalations';
 return <section aria-labelledby="workflow-title" style={{maxWidth:1100}}><header><h1 id="workflow-title">{title}</h1><p style={{color:'#94a3b8'}}>WF-1 enterprise workflow engine · tenant scoped · server authorized</p></header>
 {mode==='definitions'&&<form onSubmit={create} style={{display:'grid',gridTemplateColumns:'minmax(160px,1fr) minmax(220px,2fr) auto',gap:12,margin:'24px 0',padding:20,background:'#1e293b',borderRadius:8}}><label>Key<input aria-label="Workflow key" required pattern="[a-z][a-z0-9-]*" value={key} onChange={e=>setKey(e.target.value)} style={{display:'block',width:'100%',padding:10}}/></label><label>Name<input aria-label="Workflow name" required value={name} onChange={e=>setName(e.target.value)} style={{display:'block',width:'100%',padding:10}}/></label><button type="submit" style={{alignSelf:'end',padding:'11px 18px'}}>Create draft</button></form>}
 {loading&&<p role="status">Loading workflows…</p>}{error&&<div role="alert" style={{color:'#fca5a5',padding:16}}>{error}<button onClick={load} style={{marginLeft:12}}>Retry</button></div>}
 {!loading&&!error&&data.length===0&&<div style={{padding:32,border:'1px dashed #475569',borderRadius:8}}>No {title.toLowerCase()} found.</div>}
 <div style={{display:'grid',gap:12}}>{data.map((item,index)=><article key={item.id||index} tabIndex={0} style={{padding:18,background:'#1e293b',border:'1px solid #334155',borderRadius:8}}><h2 style={{fontSize:'1rem',margin:'0 0 8px'}}>{item.name||item.definition_name||item.definition_key||item.id||title}</h2><dl style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8,margin:0}}>{Object.entries(item).filter(([k])=>['key','status','version','version_count','current_state','assignment_type','due_at','active_instances','open_work_items','due_timers','breached_slas'].includes(k)).map(([k,v])=><div key={k}><dt style={{color:'#94a3b8'}}>{k.replace(/_/g,' ')}</dt><dd style={{margin:0}}>{String(v??'—')}</dd></div>)}</dl></article>)}</div>
 </section>;
}
